[theme]

# Primary accent for interactive elements
primaryColor = '#619ED0'

# Background color for the main content area
backgroundColor = '#74737C'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace" 